### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by SduyXD** [rgbkrk/atom-achievements#15]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
AchievementsView.achieve (/Users/sduy/.atom/packages/achievements/lib/achievements-view.coffee:32:9)
```

**Comment by rgbkrk** [comment]
This makes me so glad to know someone actually uses this package. :wink:

There's quite a bit to adapt to the new API with regards to events too. Not sure when I can carve out time for it, but I'd like to.

**Comment by SduyXD** [comment]
i change
from :     atom.workspaceView.append(this)
to :         atom.views.getView(atom.workspace) .append(this)

and it seems to be fixed, so i can do a pull request doing it?

**Comment by rgbkrk** [comment]
@SduyXD Absolutely.

**Comment by SduyXD** [comment]
Check pull request https://github.com/rgbkrk/atom-achievements/pull/16
